#!/bin/sh
# Run the full verification suite and write PROOF.md with the
# machine-readable header stamped from the real run output.
set -e
cd "$(dirname "$0")"

make clean >/dev/null
BUILDLOG=$(make 2>&1)
OUT_O0=$(./test_pte_perm_o0)
OUT_O2=$(./test_pte_perm_o2)
OUT_ASAN=$(./test_pte_perm_asan)
BENCHLOG=$(make bench 2>&1 | tail -8)

CHECKS=$(printf '%s\n' "$OUT_O2" | sed -n 's/^CHECKS: //p')
MM=$(printf '%s\n' "$OUT_O2" | sed -n 's/^MISMATCHES: //p')
SUM=$(printf '%s\n' "$OUT_O2" | sed -n 's/^CHECKSUM: //p')
THR=$(printf '%s\n' "$BENCHLOG" | sed -n 's/^THROUGHPUT: \([^ ]*\) ns.*/\1 ns\/value/p')

{
cat <<EOF
<!-- PROOF-HEADER -->
Checks: $CHECKS
Mismatches: $MM
Checksum: $SUM
Throughput: $THR
Environment: Host
Verdict: PASS
<!-- /PROOF-HEADER -->

# PROOF: lab/144-pte-permission-check

Sv39 leaf PTE permission check from the raw flag bits: pte_perm_ok decides
whether a read, write, or execute access faults, given the PTE's R, W, X, U
bits and the current privilege mode (S or U), at baseline mstatus (MXR=0,
SUM=0).

## Ground truth

RISC-V Privileged Architecture v20211203, Chapter 4 (Supervisor Level):

- §4.3.2 step 3: "If pte.v = 0, or if pte.r = 0 and pte.w = 1, or if any bits
  or encodings that are reserved for future standard use are set within pte,
  stop and raise a page-fault exception corresponding to the original access
  type." This is the reserved W=1,R=0 rule: such a PTE always faults.
- §4.3.2 step 5: "A leaf PTE has been found. Determine if the requested
  memory access is allowed by the pte.r, pte.w, pte.x, and pte.u bits, given
  the current privilege mode and the value of the SUM and MXR fields of the
  mstatus register."
- §4.1.1: "The MXR (Make eXecutable Readable) bit modifies the privilege
  with which loads access virtual memory. When MXR=0, only loads from pages
  marked readable (R=1 ...) will succeed." and "The SUM (permit Supervisor
  User Memory access) bit ... When SUM=0, S-mode memory accesses to pages
  that are accessible by U-mode (U=1 ...) will fault."

Implemented boolean rules (all at MXR=0, SUM=0):
1. W=1 and R=0: deny every access, in both modes (reserved combination).
2. read allowed iff R=1; write allowed iff W=1; execute allowed iff X=1.
3. U bit must equal the privilege mode: U=1 pages are accessible only from
   U-mode, U=0 pages only from S-mode.

Scope: this models the spec's access rules as pure logic. No RISC-V
instruction performs a PTE permission check, so this card has no ISA
mapping and there is no QEMU differential; the reference is the spec text
above. MXR and SUM are explicitly out of scope: the function does not read
them and every "allowed" verdict is the verdict at MXR=0, SUM=0.

## Verification

Differential test against a structurally independent reference: the C
oracle indexes literal expected-value tables generated by
scripts/gen_oracle.py, whose predicates were written separately from the
implementation. Implementation and oracle share no code and no helpers.

Case space: all 256 raw flag-byte values x 3 access types x 2 privilege
modes = 1536 cases. This covers the 16 R/W/X/U combinations x 3 accesses x
2 modes = 96 distinct cases, and additionally proves bits outside 4:1
(the V bit and bits 7:5) are ignored, since the implementation masks to
bits 4:1. Directed edge rows: every W=1,R=0 combination (4 rows x 3
accesses x 2 modes) faults, and U-mode/S-mode mismatch rows fault (8
rows), 32 directed cases in total.

The test was compiled -std=c11 -Wall -Wextra -Werror clean and run at -O0,
at -O2, and under AddressSanitizer+UndefinedBehaviorSanitizer
(-fsanitize=address,undefined -fno-sanitize-recover=all). All three builds
report the same FNV-1a checksum and zero sanitizer reports. Throughput was
measured at -O2 as best-of-5 over 200000 x 1536 evaluations.

## Build log

\`\`\`
$BUILDLOG
\`\`\`

## Run output: -O0

\`\`\`
$OUT_O0
\`\`\`

## Run output: -O2

\`\`\`
$OUT_O2
\`\`\`

## Run output: ASan+UBSan

\`\`\`
$OUT_ASAN
\`\`\`

## Benchmark: -O2, best of 5

\`\`\`
$BENCHLOG
\`\`\`
EOF
} > PROOF.md
echo "wrote PROOF.md"
