#ifndef ORACLE_H
#define ORACLE_H

#include <stdint.h>

/*
 * oracle_perm_ok: structurally independent reference for pte_perm_ok.
 * Implemented as a plain index into literal tables generated by
 * scripts/gen_oracle.py. It shares no code or helpers with pte_perm.c.
 * access/mode use the same 0/1/2 and 0/1 integer coding as perm_access_t
 * and perm_mode_t; flags are the raw PTE flag byte in true bit positions.
 */
int oracle_perm_ok(uint8_t flags, int access, int mode);

#endif
