#!/usr/bin/env python3
"""Generate oracle_table.h: an independent expected-results table for the
lab/144-pte-permission-check differential test.

The rules below are written independently of the C implementation (no shared
code or shared helper functions); the C oracle reads these tables as plain
literals, so the differential test compares the implementation against a
structurally independent reference.
"""

ACCESSES = ["READ", "WRITE", "EXEC"]
MODES = ["SMODE", "UMODE"]


def expect_ok(flags4, access, mode):
    """flags4: the 4-bit R/W/X/U nibble (bit0=R, bit1=W, bit2=X, bit3=U)."""
    r = bool(flags4 & 0b0001)
    w = bool(flags4 & 0b0010)
    x = bool(flags4 & 0b0100)
    u = bool(flags4 & 0b1000)
    if w and not r:
        return 0  # reserved combination always faults
    if u != (mode == 1):
        return 0  # with SUM=0, U must match the privilege mode
    if access == 0:  # READ
        return int(r)
    if access == 1:  # WRITE
        return int(w)
    return int(x)  # EXEC


def main():
    lines = []
    lines.append("/* Generated by scripts/gen_oracle.py. Do not edit by hand. */")
    lines.append("#ifndef ORACLE_TABLE_H")
    lines.append("#define ORACLE_TABLE_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    for ai, aname in enumerate(ACCESSES):
        for mi, mname in enumerate(MODES):
            row = ", ".join(str(expect_ok(f, ai, mi)) for f in range(16))
            lines.append("static const uint8_t oracle_%s_%s[16] = { %s };" % (aname, mname, row))
    lines.append("")
    lines.append("/* tables indexed as oracle_tbl[access][mode][nibble] */")
    lines.append("static const uint8_t *oracle_tbl[3][2] = {")
    lines.append("    { oracle_READ_SMODE,  oracle_READ_UMODE },")
    lines.append("    { oracle_WRITE_SMODE, oracle_WRITE_UMODE },")
    lines.append("    { oracle_EXEC_SMODE,  oracle_EXEC_UMODE },")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    with open("oracle_table.h", "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote oracle_table.h")


if __name__ == "__main__":
    main()
